public class Address {
    public void homeAddress() {
        string name = 'Elif';
        system.debug('Your name: ' + name);

        integer familyMembers = 5;
        system.debug('Total number of members in your family: ' + familyMembers);

        string houseName = 'Home';
        system.debug('House Name: ' + houseName);

        string houseNumber = '1100';
        system.debug('House Number: ' + houseNumber);

        string streetName = 'Sunrise';
        system.debug('Street Name: ' + streetName);

        string cityName = 'Dallas';
        system.debug('City Name: ' + cityName);

        string stateName = 'Tx';
        system.debug('State Name: ' + stateName);

        string stateIsoCode = 'Tx-usa';
        system.debug('State ISO Code: ' + stateIsoCode);

        string countryName = 'USA';
        system.debug('Country Name: ' + countryName);

        string countryIsoCode = 'Tx';
        system.debug('Country ISO Code: ' + countryIsoCode);

        string zipCode = '75002';
        system.debug('Zip Code: ' + zipCode);

        Boolean currentHome = true;
        system.debug('Is this your current home?: ' + currentHome);

    }
}