AirlineTickets ticket1 = new AirlineTickets();

ticket1.arrivalCity = 'New York';
ticket1.departureCity = 'Los Angeles';
ticket1.flightNumber = '14563';
ticket1.seatAssignment = '17T';
system.debug(ticket1);
ticket1.printTicket();

AirlineTickets ticket2 = new AirlineTickets();

ticket2.arrivalCity = 'Istanbul';
ticket2.departureCity = 'Berlin';
ticket2.flightNumber = '23654';
ticket2.seatAssignment = '49A';
system.debug(ticket1);
ticket2.printTicket();

    
